INSERT INTO user VALUES(1, 'Celeste', 'temp.png');
INSERT INTO user VALUES(2, 'Tresa', 'temp.png');
INSERT INTO user VALUES(3, 'Kathe', 'temp.png');
INSERT INTO user VALUES(4, 'Marla', 'temp.png');
INSERT INTO user VALUES(5, 'Chadwick', 'temp.png');
INSERT INTO user VALUES(6, 'Branden', 'temp.png');
INSERT INTO user VALUES(7, 'Stacey', 'temp.png');
INSERT INTO user VALUES(8, 'Aldo', 'temp.png');
INSERT INTO user VALUES(9, 'Fe', 'temp.png');
INSERT INTO recipe VALUES(1, 'Lucirr', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(2, 'Keha', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(3, 'Wiggles', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(4, 'Sparkle', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(5, 'Cipanr', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(6, 'Ballon', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(7, 'Lasis', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(8, 'Blurp', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO recipe VALUES(9, 'ThantYeitha', 'temp.png', '15 min', '15 min', '30 min', '1. Cook 2. Server');
INSERT INTO ingredient VALUES(1, 'Lucirr');
INSERT INTO ingredient VALUES(2, 'Keha');
INSERT INTO ingredient VALUES(3, 'Wiggles');
INSERT INTO ingredient VALUES(4, 'Sparkle');
INSERT INTO ingredient VALUES(5, 'Cipanr');
INSERT INTO ingredient VALUES(6, 'Ballon');
INSERT INTO ingredient VALUES(7, 'Lasis');
INSERT INTO ingredient VALUES(8, 'Blurp');
INSERT INTO ingredient VALUES(9, 'ThantYeitha');
INSERT INTO ingredient VALUES(10, 'FlyingFungus');
INSERT INTO ingredient VALUES(11, 'Hynryac');
INSERT INTO ingredient VALUES(12, 'Gullet');
INSERT INTO ingredient VALUES(13, 'Sunshine');
INSERT INTO ingredient VALUES(14, 'Dushan');
INSERT INTO ingredient VALUES(15, 'Kaleida');
INSERT INTO ingredient VALUES(16, 'Raich');
INSERT INTO ingredient VALUES(17, 'Serenity');
INSERT INTO ingredient VALUES(18, 'Glider');
INSERT INTO ingredient VALUES(19, 'Castor');
INSERT INTO event VALUES(1, 'event1', 'uci', NOW());
INSERT INTO event VALUES(2, 'event2', 'uci', NOW());
INSERT INTO event VALUES(3, 'event3', 'uci', NOW());
INSERT INTO event VALUES(4, 'event4', 'uci', NOW());
INSERT INTO event VALUES(5, 'event5', 'uci', NOW());
INSERT INTO event VALUES(6, 'event6', 'uci', NOW());
INSERT INTO event VALUES(7, 'event7', 'uci', NOW());
INSERT INTO event VALUES(8, 'event8', 'uci', NOW());
INSERT INTO event VALUES(9, 'event9', 'uci', NOW());
INSERT INTO event VALUES(10, 'event10', 'uci', NOW());
INSERT INTO event VALUES(11, 'event11', 'uci', NOW());
INSERT INTO event VALUES(12, 'event12', 'uci', NOW());
INSERT INTO event VALUES(13, 'event13', 'uci', NOW());
INSERT INTO event VALUES(14, 'event14', 'uci', NOW());
INSERT INTO event VALUES(15, 'event15', 'uci', NOW());
INSERT INTO event VALUES(16, 'event16', 'uci', NOW());
INSERT INTO event VALUES(17, 'event17', 'uci', NOW());
INSERT INTO event VALUES(18, 'event18', 'uci', NOW());
INSERT INTO event VALUES(19, 'event19', 'uci', NOW());
INSERT INTO ingredientsInRecipe VALUES(1, 1, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(1, 2, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(2, 2, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(2, 3, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(3, 3, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(3, 4, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(4, 4, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(4, 5, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(5, 5, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(5, 6, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(6, 6, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(6, 7, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(7, 7, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(7, 8, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(8, 8, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(8, 9, '1 cup');
INSERT INTO ingredientsInRecipe VALUES(9, 9, '2 cups');
INSERT INTO ingredientsInRecipe VALUES(9, 10, '1 cup');
INSERT INTO usersAtEvents VALUES(1, 1, 'participant');
INSERT INTO usersAtEvents VALUES(2, 2, 'participant');
INSERT INTO usersAtEvents VALUES(3, 3, 'participant');
INSERT INTO usersAtEvents VALUES(4, 4, 'participant');
INSERT INTO usersAtEvents VALUES(5, 5, 'participant');
INSERT INTO usersAtEvents VALUES(6, 6, 'participant');
INSERT INTO usersAtEvents VALUES(7, 7, 'participant');
INSERT INTO usersAtEvents VALUES(8, 8, 'participant');
INSERT INTO usersAtEvents VALUES(9, 9, 'participant');
INSERT INTO usersRecipes VALUES(1, 1);
INSERT INTO usersRecipes VALUES(2, 2);
INSERT INTO usersRecipes VALUES(3, 3);
INSERT INTO usersRecipes VALUES(4, 4);
INSERT INTO usersRecipes VALUES(5, 5);
INSERT INTO usersRecipes VALUES(6, 6);
INSERT INTO usersRecipes VALUES(7, 7);
INSERT INTO usersRecipes VALUES(8, 8);
INSERT INTO usersRecipes VALUES(9, 9);
INSERT INTO recipesAtEvents VALUES(1, 1);
INSERT INTO recipesAtEvents VALUES(2, 2);
INSERT INTO recipesAtEvents VALUES(3, 3);
INSERT INTO recipesAtEvents VALUES(4, 4);
INSERT INTO recipesAtEvents VALUES(5, 5);
INSERT INTO recipesAtEvents VALUES(6, 6);
INSERT INTO recipesAtEvents VALUES(7, 7);
INSERT INTO recipesAtEvents VALUES(8, 8);
INSERT INTO recipesAtEvents VALUES(9, 9);
